### Create Event
# @name createEvent
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "title": "Test Event",
    "timezone": "America/New_York",
    "startsAt": "2026-01-29T00:00:00Z",
    "endsAt": "2026-01-29T01:00:00Z"
}

### List Events
GET http://localhost:3000/api/events
Content-Type: application/json

### Get Event
GET http://localhost:3000/api/events/{{createEvent.response.body.id}}
Content-Type: application/json
